# Generated by Django 5.0.2 on 2024-02-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.AddField(
            model_name='customer',
            name='phoneNumber',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
